#1
A Python library is a collection of pre-written code that provides functionality to perform common tasks without having to write the code from scratch. These libraries contain functions, classes, and modules that help with specific operations, such as mathematics, data manipulation, web development, machine learning, and more.

#2
NumPy Array: Optimized for numerical computations, faster, supports element-wise operations, and is memory efficient.
Python List: More flexible in terms of holding different data types, but slower for numerical tasks and lacks advanced mathematical operations.

In [3]:
#3
import numpy as np
a=[[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]]
a=np.array(a)
print(np.ndim(a))
print(np.shape(a))

2
(3, 4)


In [5]:
#4
a[0]

array([1, 2, 3, 4])

In [7]:
#5
a[2,3]

12

In [9]:
#6
a[1::2,1::2]

array([[6, 8]])

In [11]:
#7
np.random.rand(3,3)

array([[0.06977851, 0.94437396, 0.93439766],
       [0.83861733, 0.36452807, 0.73365516],
       [0.76128247, 0.57751737, 0.6984853 ]])

In [13]:
#8
#the major difference between random.rand and random.randn is that rand gives positive numbers and randn gives negative values.

In [15]:
#9
np.expand_dims(a,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [17]:
#10
np.transpose(a)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [19]:
#11
A=np.array(a)
B=np.array(a)
print(A*B)
print()
print(np.dot(A,B.T))
print()
print(A+B)
print()
print(B-A)
print()
print(B/A)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
#12
A.byteswap()

array([[ 16777216,  33554432,  50331648,  67108864],
       [ 83886080, 100663296, 117440512, 134217728],
       [150994944, 167772160, 184549376, 201326592]])

In [27]:
#13
# np.linalg.inv function work to gets the inverse of square matrix A-1.
a=np.array([[2,4,5],[3,4,4],[4,1,1]])
np.linalg.inv(a)

array([[ 0.        , -0.07692308,  0.30769231],
       [-1.        ,  1.38461538, -0.53846154],
       [ 1.        , -1.07692308,  0.30769231]])

In [37]:
#14
# np.reshape is reshape the matrix.
np.reshape(a,(1,9))

array([[2, 4, 5, 3, 4, 4, 4, 1, 1]])

In [39]:
#15
#Broadcasting in NumPy refers to the ability of NumPy to perform element-wise operations on arrays of different shapes without explicitly reshaping them. Broadcasting makes array arithmetic more efficient by automatically expanding the smaller array to match the shape of the larger array during operations, without creating unnecessary copies of data.
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[10, 20, 30]])

# Broadcasting the smaller array B across A
result = A + B

print(result)


[[11 22 33]
 [14 25 36]
 [17 28 39]]
